spring:
  application:
    name: final

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token:
    header: Authorization
    expiration:

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    try-it-out-enabled: true
